/*
	AUTHOR: Fábio Pereira da Silva
	YEAR: 2019
	LICENSE: MIT
	EMAIL: fabioegel@gmail.com or fabioegel@protonmail.com
*/

// This tools exports public key prime256r1 curve generated by openssl tools to FIOT bootloader verify signed firmware.


//Qua 10 Jul 2019 00:08:55 -03

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mbedtls/pk.h"
#include "mbedtls/platform.h"
#include "mbedtls/error.h"

#include "f_mbedtls_util.h"

#define MAJOR_VER (uint32_t)1
#define MINOR_VER (uint32_t)0

#define FIOT_USAGE "\nUsage \"%s\" -mpk1 <master_pub_key1.pem> -mpk2 <master_pub_key2.pem> -mpk3 <master_pub_key3.pem> -of <out.mpk>\n"
#define FIOT_NAME "fiot_export_master_public_key"
#define FIOT_MSG "\n(C) 2019 - FIOT PUBLIC KEY EXPORT TOOL\n\n" \
                      "Fábio Pereira da Silva\n\n"\
                      "Ver.: %d.%d\n" \
                      FIOT_USAGE\
                      "\n\n\n"

#define MISSING_PK "\nMissing master PUBLIC %s key file\n"
#define F_MPK1 1
#define F_MPK2 2
#define F_MPK3 4
//#define NUM_MPK 3

int main(int argc, char **argv)
{
   int err=0;
   int i;
   int m;
   char *mpk[3]={NULL};
   char *output_file_name=NULL;
   char buf[1024];
   char PUBLIC_KEY_STREAM[NUM_MPK*64];
   mbedtls_pk_context public_key;
   FILE *f;

   if (argc==1) {
      printf(FIOT_MSG, MAJOR_VER, MINOR_VER, FIOT_NAME);
      return 0;
   }

   for (i=1;i<argc;i++) {
      if (strcmp(argv[i], "-mpk1")==0) {
         if (argc==++i) {
            printf(MISSING_PK, "1");
            return 1;
         } else {
            err|=F_MPK1;
            mpk[0]=argv[i];
         }
      } else if (strcmp(argv[i], "-mpk2")==0) {
         if (argc==++i) {
            printf(MISSING_PK, "2");
            return 1;
         } else {
            err|=F_MPK2;
            mpk[1]=argv[i];
         }
      } else if (strcmp(argv[i], "-mpk3")==0) {
         if (argc==++i) {
            printf(MISSING_PK, "3");
            return 1;
         } else {
            err|=F_MPK3;
            mpk[2]=argv[i];
         }
      } else if (strcmp(argv[i], "-of")==0) {
         if (argc==++i) {
            printf("\nMissing output file\n");
            return 1;
         } else
            output_file_name=argv[i];
      } else {
         printf("\nMissing argument\n"FIOT_USAGE, FIOT_NAME);
         return 1;
      }
   }

   if (err==0) {
      printf("\nError. At least one master public key must be added\n");
      return 1;
   }

   if (output_file_name==NULL) {
      printf("\nERROR. Select an output file name\n");
      return 1;
   }

   printf("\nInitializing...\n");

   memset(PUBLIC_KEY_STREAM, 0, sizeof(PUBLIC_KEY_STREAM));

   mbedtls_pk_init(&public_key);

   m=0;

   for (i=0;i<NUM_MPK;i++) {

      if (mpk[i]!=NULL) {

         err=mbedtls_pk_parse_public_keyfile(&public_key, mpk[i]);

         printf("\nOpening file \"%s\" ... ", mpk[i]);

         if (err) {
            mbedtls_pk_free(&public_key);
            mbedtls_strerror(err, (char *)buf, sizeof(buf));
            mbedtls_printf("Error opening file. Is this public PEM file?\n ! mbedtls_pk_parse_public_keyfile returned -0x%04x - %s\n\n", -err, buf);
            return err;
         }

         printf(" [ ok ]");

         printf("\nVerifying public key type ...");

         if (mbedtls_pk_get_type(&public_key)!=MBEDTLS_PK_ECKEY) {
            mbedtls_pk_free(&public_key);
            printf("\nError: File (master public key) \"%s\" is not an ECKEY\n", mpk[i]);
            return 1;
         }

         printf(" [ ok ]");

         printf("\nVerifying curve SECP256v1 ...");

         if ((mbedtls_pk_ec(public_key)->grp.id)!=MBEDTLS_ECP_DP_SECP256R1) {
            mbedtls_pk_free(&public_key);
            printf("\nError. FIOT bootloader works only with signed SECP256v1 curve\n");
            return 1;
         }

         printf(" [ ok ]");

         printf("\nExtracting public key file in \"%s\" file...", mpk[i]);

         err=f_extract_public_key(mbedtls_pk_ec(public_key), (char *)(PUBLIC_KEY_STREAM+m));

         if (err==0) {
            mbedtls_pk_free(&public_key);
            printf("\nError on extracting public key in \"%s\" file\n", mpk[i]);
            return 1;
         }

         fhex2str((unsigned char *)(PUBLIC_KEY_STREAM+m), err, buf);

         printf("\nAdding master public key \"%s\" to file stream ...", buf);

         printf(" [ ok ]");

         //m+=err;

         mbedtls_pk_free(&public_key);
         printf("\n===================\n");

      }
      m+=64;
   }
   fhex2str(PUBLIC_KEY_STREAM, sizeof(PUBLIC_KEY_STREAM), buf);
   printf("\nRaw data stream \"%s\" will be added to file \"%s\"...", buf, output_file_name);
   printf("\nCreating file \"%s\" ...", output_file_name);

   f=fopen(output_file_name, "w");

   if (!f) {
      printf("\nError. Can't create file \"%s\". Aborting...\n", output_file_name);
      return 1;
   }

   if (fwrite(PUBLIC_KEY_STREAM,1,sizeof(PUBLIC_KEY_STREAM),f)^sizeof(PUBLIC_KEY_STREAM)) {
      fclose(f);
      printf("\nError writing \"%s\" file. Aborting ...\n", output_file_name);
      return 1;
   }

   printf("\nClosing file \"%s\" ...", output_file_name);

   fclose(f);

   printf(" [ ok ]");
   printf("\nDone\n");

   return 0;
}
